AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

# Metrics

Metrics/BlockLength:
  Max: 240

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 240

# Documentation

Style/Documentation:
  Enabled: false

# Style

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SymbolArray:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: false

Layout/LineLength:
  Max: 120
